import '../styles/globals.scss'
import '../styles/normalize.css'
import { ThemeProvider } from '@/components/contexts/ThemeContext'
// import { DataProvider } from '@/components/contexts/DataContext'
import ThemeToggleButton from '@/components/ToggleThemeButton'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <head>
        <link rel='preconnect' href='https://fonts.googleapis.com' />
        <link
          rel='preconnect'
          href='https://fonts.gstatic.com'
          crossOrigin='true'
        />
        <link
          href='https://fonts.googleapis.com/css2?family=Roboto+Flex:wght@100..900&family=Concert+One&display=swap'
          rel='stylesheet'
        />
      </head>
      <body suppressHydrationWarning={true}>
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  )
}
