import '../styles/globals.css'
import '../styles/normalize.css'
import Test from '@/components/Test'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <head>
        <link rel='preconnect' href='https://fonts.googleapis.com' />
        <link
          rel='preconnect'
          href='https://fonts.gstatic.com'
          crossOrigin='true'
        />
        <link
          href='https://fonts.googleapis.com/css2?family=Roboto+Flex:wght@100..900&family=Concert+One&display=swap'
          rel='stylesheet'
        />
      </head>
      <body suppressHydrationWarning={true}>
        {children}
        <Test />
      </body>
    </html>
  )
}
